"""alteracao no campo email para 100 chars

Revision ID: 8b5d507844a4
Revises: 70be69d705e5
Create Date: 2024-12-26 11:20:46.648548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5d507844a4'
down_revision: Union[str, None] = '70be69d705e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
    # ### commands auto generated by Alembic - please adjust! ###
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
    # ### commands auto generated by Alembic - please adjust! ###
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
